### ISSUE TITLE
Add link from the repo to the website

### ISSUE THREAD

**Issue by hoijui** [mahogny/docubricks#17]
There is an option for that on GitHub, right on the main repo page, next to the project description line.

**Comment by MakerTobey** [comment]
Thanks - this had already been placed at the main repository, but the more the better. Now also done for the Editor and Viewer Repo

![Screenshot 2020-04-20 at 22 47 52](https://user-images.githubusercontent.com/14097042/79798254-02c4c780-8359-11ea-8483-8a73c2c21b66.png)

**Comment by hoijui** [comment]
ahhh I see.. makes sense there ... I did not think of looking there.
perfect now! :-)
